"use client";
import Photo from "@/main/components/item";
import { useState, useEffect, useCallback } from "react";
import Gallery from "react-photo-gallery";
import Footer from "@/main/components/footer";

export default function About() {
  const [images, setImages] = useState([]);

  const getData = useCallback(async () => {
    const res = await fetch(
      "https://stable-diff-api-production.up.railway.app/api/v1/db/posts",
    );
    const temp = await res.json();
    const images = temp.data;

    setImages((prev) => [...prev, ...images]);
  }, []);

  const isScrollBottom = () => {
    if (
      window.innerHeight + document.documentElement.scrollTop ===
      document.documentElement.offsetHeight
    ) {
      return true;
    }
    return false;
  };

  useEffect(() => {
    const onScroll = async () => {
      if (isScrollBottom()) {
        await getData();
      }
    };
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, [getData]);

  useEffect(() => {
    getData();
  }, [getData]);

  return (
    <div>
      <div className="h-20"></div>

      <div className="text-center w-full ">
        <p className="p-4 text-3xl">
          Over 500 Images generated by 410 unique visitors from 41 Countries,
          900+ Page views.
        </p>
      </div>
      <div className="h-10"></div>
      <div className="w-full ">
        <div className="grid grid-cols-fluid">
          {images.length > 0 &&
            images.map((item, index) => (
              <Photo
                id={`${item._id}-photo-${index}`}
                rt={item._id}
                key={item._id}
                prompt={item.prompt}
                steps={item.steps}
                sampler_index={item.sampler_index}
                cfg_scale={item.cfg_scale}
                image={item.image}
              />
            ))}
        </div>
      </div>
      <div className="h-10"></div>
      {/* <Gallery photos={images} /> */}
      <Footer />
    </div>
  );
}
