export const surpriseMePrompts = [
  "airy, pin-up, sci-fi, steam punk, very deitaled, realistic,  figurative painter, fineart, Oil painting on canvas, beautiful painting by Daniel F Gerhartz",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "RPG Map, battle map, a0 landscape, dragon hunting in the dark forest, dragon cave in center, two castles at the end, saxon forest, 2d, 8k, waved",
  "hyperrealistic full length portrait of gorgeous goddess | standing in field full of flowers | detailed gorgeous face!! | full body!! | skimpy armor | god rays | intricate | elegant | realistic | hyperrealistic | cinematic | character design | concept art | highly detailed | illustration | digital art | digital painting | depth of field",
  "“Vibrant colors,” “Geometric shapes,” “Abstract patterns,” “Movement and flow,” “Texture and layers.”",
  "“Dreamlike,” “Surreal landscapes,” “Mystical creatures,” “Twisted reality,” “Surreal still life.”",
  "“Majestic mountains,” “Lush forests,” “Glittering lakes,” “Desert dunes,” “Golden sunsets.”",
  "“Emotive eyes,” “Intense gazes,” “Contemplative mood,” “Expressive gestures,” “Stylized poses”.",
  "“Candid moments,” “Urban landscapes,” “Street life,” “Stories in motion,” “Street portraits.”",
  "“Lit cityscapes,” “Starry skies,” “Moonlit landscapes,” “Night time portraits,” “Long exposures.”",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "A winter full of regret: An art piece depicting the feeling of regret in a winter setting, with a focus on snow and frozen landscapes.",
  "Fairy tales: A whimsical, dreamy image of a cute animal surrounded by elements inspired by fairy tales, such as magical creatures and enchanted landscapes.",
  "5 and Octane Render: An art piece showcasing a cute animal with a 5 aspect ratio and rendered",
  "A stylized photo of a well-known comic book superhero, such as Spider-Man, surfing on a giant taco while eating a hotdog and drinking a Pepsi.",
  "An impressionist photo of a sunset over the Great Wall of China made of gumdrops ",
  "An abstract photo of a red Ferrari car driving through a sea of Legos",
  "A haunting, atmospheric ghost town in the style of Tim Burton",
  "A futuristic, neon-lit cityscape in the style of TRON",
];
